# Generated by Django 3.1.1 on 2020-09-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cpf', models.PositiveIntegerField(max_length=11)),
                ('date', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
