# Generated by Django 3.1.1 on 2020-09-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='cpf',
            field=models.PositiveIntegerField(),
        ),
    ]
