# Generated by Django 3.1.1 on 2020-09-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_auto_20200902_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
