# Generated by Django 3.1.1 on 2020-09-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_auto_20200902_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='querycovid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
