# Generated by Django 3.1.1 on 2020-09-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_remove_scheduling_querycovid'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='categoryUser',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scheduling',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
